### PR TITLE
Ref #339 jcache fixes and integration test

### LINKED ISSUE #339: Add camel-jcache integration tests
camel-jcache fixes and  integration tests with ehcache and hazelcast

### PR DESCRIPTION
**Pull request by f2par0**
fixes #339 
Some fixes in hazelcast are necessary to be able to activate jcache api
Reintegrate classes from camel-jcache-osgi with a fix to handle comments in the service file. (class name in not necessarily in the first read line)
tests with ehcache and hazelcast cache

### CODE REVIEW

File: components/camel-jcache/src/main/java/org/apache/camel/component/jcache/osgi/Activator.java [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+    public void start(BundleContext context) throws Exception {
+        Object factory = new OSGiCacheManagerFactory();
+        registration = context.registerService(JCacheManagerFactory.class.getName(), factory, null);
+    }
+
+    @Override
+    public void stop(BundleContext context) throws Exception {
+        // release the reference
+        if (registration != null) {
+            context.ungetService(registration.getReference());
```
Comment (essobedo) [inline components/camel-jcache/src/main/java/org/apache/camel/component/jcache/osgi/Activator.java:37]: I think it should rather be registration.unregister()

File: components/camel-jcache/src/main/java/org/apache/camel/component/jcache/osgi/OSGiCacheManager.java [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+
+                                @Override
+                                protected Enumeration findResources(String name) throws IOException {
+                                    try {
+                                        return acl.getResources(name);
+                                    } catch (IOException e) {
+                                        return bundle.getResources(name);
+                                    }
+                                }
+                            };
```
Comment (essobedo) [inline components/camel-jcache/src/main/java/org/apache/camel/component/jcache/osgi/OSGiCacheManager.java:107]: This should not be needed as SPI is managed by spifly

File: tests/features/camel-jcache/src/main/java/org/apache/karaf/camel/test/CamelJcacheHzRouteSupplier.java [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+        immediate = true,
+        service = CamelRouteSupplier.class
+)
+public class CamelJcacheHzRouteSupplier extends AbstractCamelJcacheRouteSupplier {
+
+    public static final String PROVIDER_CLASS = "com.hazelcast.cache.HazelcastCachingProvider";
+
+    @Override
+    public void configure(CamelContext camelContext) {
+        System.setProperty("hazelcast.jcache.provider.type", "member");
```
Comment (essobedo) [inline tests/features/camel-jcache/src/main/java/org/apache/karaf/camel/test/CamelJcacheHzRouteSupplier.java:33]: Use `ClusterProperty.JCACHE_PROVIDER_TYPE.setSystemProperty("member")` instead

File: tests/features/camel-jcache/src/main/java/org/apache/karaf/camel/test/CamelJcacheEhRouteSupplier.java [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+import org.osgi.service.component.annotations.Component;
+
+@Component(
+        name = "karaf-camel-jcache-eh-test",
+        immediate = true,
+        service = CamelRouteSupplier.class
+)
+public class CamelJcacheEhRouteSupplier extends AbstractCamelJcacheRouteSupplier {
+
+    public static final String PROVIDER_CLASS = "org.ehcache.jsr107.EhcacheCachingProvider";
```
Comment (essobedo) [inline tests/features/camel-jcache/src/main/java/org/apache/karaf/camel/test/CamelJcacheEhRouteSupplier.java:28]: Can we use `EhcacheCachingProvider.class.getName()` instead?

File: tests/features/camel-jcache/src/main/java/org/apache/karaf/camel/test/CamelJcacheHzRouteSupplier.java [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+import org.osgi.service.component.annotations.Component;
+
+@Component(
+        name = "karaf-camel-jcache-hz-test",
+        immediate = true,
+        service = CamelRouteSupplier.class
+)
+public class CamelJcacheHzRouteSupplier extends AbstractCamelJcacheRouteSupplier {
+
+    public static final String PROVIDER_CLASS = "com.hazelcast.cache.HazelcastCachingProvider";
```
Comment (essobedo) [inline tests/features/camel-jcache/src/main/java/org/apache/karaf/camel/test/CamelJcacheHzRouteSupplier.java:29]: ditto, let's get the name from the class instead of hard coding it

File: tests/features/camel-jcache/src/main/java/org/apache/karaf/camel/test/CamelJcacheEhRouteSupplier.java (hunk 4 above)
Comment (f2par0) [reply tests/features/camel-jcache/src/main/java/org/apache/karaf/camel/test/CamelJcacheEhRouteSupplier.java:28]: it's possible, but it requires to add a maven dependency to Ehcache and an import. What do you prefer ?

Comment (essobedo) [reply tests/features/camel-jcache/src/main/java/org/apache/karaf/camel/test/CamelJcacheEhRouteSupplier.java:28]: I see, we can keep it like this but first we need to make sure that if we provide an invalid provider class, the test will fail

File: tests/features/camel-jcache/src/main/java/org/apache/karaf/camel/test/CamelJcacheHzRouteSupplier.java (hunk 3 above)
Comment (f2par0) [reply tests/features/camel-jcache/src/main/java/org/apache/karaf/camel/test/CamelJcacheHzRouteSupplier.java:33]: it has a side effect : importing the `com.hazelcast.spi.properties` causes the ehcache test to fail because it doesn't install the camel-hazelcast feature. so I changed the dependency to optional in maven to make it work

File: components/camel-jcache/src/main/java/org/apache/camel/component/jcache/osgi/OSGiCacheManager.java (hunk 2 above)
Comment (f2par0) [reply components/camel-jcache/src/main/java/org/apache/camel/component/jcache/osgi/OSGiCacheManager.java:107]: Tried to use the ServiceLoader to find the implementation, and then get to the bundle classloader.
It works with hazelcast but not with ecache. 
The Serviceloader works , but then when creating the cache, I get this exception which I could not resolve.

```
2024-06-13T11:37:37,104 | INFO  | RMI TCP Connection(3)-127.0.0.1 | CamelSuppliedRouteLauncher       | 46 - camel-integration-test - 4.6.0.SNAPSHOT | CamelRouteSupplier service registered: {service.id=233, service.bundleid=150, objectClass=[Ljava.lang.String;@3233b911, service.scope=bundle, component.name=karaf-camel-jcache-eh-test, osgi.ds.satisfying.condition.target=(osgi.condition.id=true), component.id=25} from the class org.apache.karaf.camel.test.CamelJcacheEhRouteSupplier
2024-06-13T11:40:33,762 | ERROR | RMI TCP Connection(3)-127.0.0.1 | Felix                            | 4 - org.ops4j.pax.logging.pax-logging-api - 2.2.7 | Bundle camel-integration-test [46] EventDispatcher: Error during dispatch. (java.lang.RuntimeException: org.apache.camel.FailedToStartRouteException: Failed to start route producer-camel-jcache-eh-test because of java.lang.IllegalStateException: Duplicate service implementation(s) found for class org.ehcache.impl.internal.spi.serialization.DefaultSerializationProvider\n		- interface org.ehcache.spi.serialization.SerializationProvider already has class org.ehcache.impl.internal.spi.serialization.D
java.lang.RuntimeException: org.apache.camel.FailedToStartRouteException: Failed to start route producer-camel-jcache-eh-test because of java.lang.IllegalStateException: Duplicate service implementation(s) found for class org.ehcache.impl.internal.spi.serialization.DefaultSerializationProvider
		- interface org.ehcache.spi.serialization.SerializationProvider already has class org.ehcache.impl.internal.spi.serialization.DefaultSerializationProvider
		- class org.ehcache.impl.internal.spi.serialization.DefaultSerializationProvider already has class org.ehcache.impl.internal.spi.serialization.DefaultSerializationProvider
	at org.apache.karaf.camel.itests.CamelSuppliedRouteLauncher.addRoutes(CamelSuppliedRouteLauncher.java:151) ~[?:?]
	at org.apache.karaf.camel.itests.CamelSuppliedRouteLauncher.serviceChanged(CamelSuppliedRouteLauncher.java:111) ~[?:?]```

Comment (f2par0) [reply components/camel-jcache/src/main/java/org/apache/camel/component/jcache/osgi/OSGiCacheManager.java:107]: Since it works like this, I don't want to spend too much time to solve this issue.

Comment (essobedo) [reply components/camel-jcache/src/main/java/org/apache/camel/component/jcache/osgi/OSGiCacheManager.java:107]: OK 👍
