### PR TITLE
Add camel-as2 integration test and fix feature

### LINKED ISSUE #406: Add camel-as2 integration test
camel-as2 integration test

### PR DESCRIPTION
**Pull request by f2par0**
Fixes #406 
camel-as2 integration test and fix feature

### CODE REVIEW

File: tests/features/camel-as2/src/main/java/org/apache/karaf/camel/test/CamelAs2RouteSupplier.java [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+    }
+
+
+    @Override
+    protected Function<RouteBuilder, RouteDefinition> consumerRoute() {
+        return builder ->
+                builder.from("as2://server/listen?requestUriPattern=/")
+                        .log("received message ${body}")
+                        .setBody(constant("OK"))
+                        ;
```
Comment (essobedo) [inline tests/features/camel-as2/src/main/java/org/apache/karaf/camel/test/CamelAs2RouteSupplier.java:97]:
```suggestion
                        .setBody(constant("OK"));
```

File: tests/features/camel-as2/src/main/java/org/apache/karaf/camel/test/CamelAs2RouteSupplier.java [hunk 2]
```diff
@@ -0,0 +1,130 @@
...
+    }
+
+    @Override
+    protected void configureProducer(RouteBuilder builder, RouteDefinition producerRoute) {
+        producerRoute.setHeader("CamelAS2.requestUri",constant(REQUEST_URI))
+                .setHeader("CamelAS2.subject",constant(SUBJECT))
```
Comment (essobedo) [inline tests/features/camel-as2/src/main/java/org/apache/karaf/camel/test/CamelAs2RouteSupplier.java:103]:
```suggestion
        producerRoute.setHeader("CamelAS2.requestUri", constant(REQUEST_URI))
                .setHeader("CamelAS2.subject", constant(SUBJECT))
```

File: tests/features/camel-as2/src/main/java/org/apache/karaf/camel/test/CamelAs2RouteSupplier.java [hunk 3]
```diff
@@ -0,0 +1,130 @@
...
+    @Override
+    public void createRoutes(RouteBuilder builder) {
+        if (consumerEnabled()) {
+            configureConsumer(consumerRoute().apply(builder));
+        }
+        if (producerEnabled()) {
+            configureProducer(
+                    builder, builder.fromF("direct:%s", getTestComponentName()).routeId("producer-%s".formatted(getTestComponentName()))
+            );
+        }
```
Comment (essobedo) [inline tests/features/camel-as2/src/main/java/org/apache/karaf/camel/test/CamelAs2RouteSupplier.java:127]: Could you please clarify why it is needed?

File: tests/features/camel-as2/src/test/java/org/apache/karaf/camel/itest/CamelAs2ITest.java [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+    public void testResultMock() throws Exception {
+        assertMockEndpointsSatisfied();
+    }
+
+    public static final class ExternalResourceProviders {
+        public static AvailablePortProvider createAvailablePortProvider() {
+            return new AvailablePortProvider(List.of("as2.port"));
+        }
+    }
+
```
Comment (essobedo) [inline tests/features/camel-as2/src/test/java/org/apache/karaf/camel/itest/CamelAs2ITest.java:48]:
```suggestion
```

File: tests/features/pom.xml [hunk 5]
```diff
@@ -41,6 +41,7 @@
         <module>camel-amqp</module>
         <module>camel-arangodb</module>
         <module>camel-asn1</module>
+        <module>camel-as2</module>
```
Comment (essobedo) [inline tests/features/pom.xml:44]:
```suggestion
        <module>camel-as2</module>
        <module>camel-asn1</module>
```

Comment (essobedo) [reply tests/features/pom.xml:44]: Numbers before letters to align with wrappers

File: tests/features/camel-as2/src/main/java/org/apache/karaf/camel/test/CamelAs2RouteSupplier.java (hunk 3 above)
Comment (f2par0) [reply tests/features/camel-as2/src/main/java/org/apache/karaf/camel/test/CamelAs2RouteSupplier.java:126]: when the producer starts before the consumer, it fails with a connection exception
` because of Failed to resolve endpoint: as2://client/send?inBody=ediMessage due to: Client HTTP connection failed `
I tried the 'lazyStartProducer' option but no effect. That's why I inverted the logic in the overriden method. I don't think it's the general rule though, so I left it as a override. I can add a comment

Comment (essobedo) [reply tests/features/camel-as2/src/main/java/org/apache/karaf/camel/test/CamelAs2RouteSupplier.java:126]: if so, yes please add a comment and you can also remove the if blocks as they are useless in this case since it always be true

**Review by essobedo — APPROVED** [review]
