### PR TITLE
Fix atom and flatpack integration tests

### LINKED ISSUE #445: Rework integration tests with checks on expected messages
camel-atom and camel-flatpack do checks on expected messages in a wrong place : configureMock instead of the tests itself.

### PR DESCRIPTION
**Pull request by f2par0**
Fixes #445 
Add a utility method `getMockEndpoint()`
Move assertion to the test, and fix errors due to differences between junit4 and  5 in the order of arguments of assertEquals()

### CODE REVIEW

File: tests/camel-integration-test/src/main/java/org/apache/karaf/camel/itests/AbstractCamelSingleFeatureResultMockBasedRouteITest.java [hunk 1]
```diff
@@ -16,6 +16,7 @@
  */
 package org.apache.karaf.camel.itests;
 
+import org.apache.camel.component.mock.MockEndpoint;
```
Comment (essobedo) [inline tests/camel-integration-test/src/main/java/org/apache/karaf/camel/itests/AbstractCamelSingleFeatureResultMockBasedRouteITest.java:19]: remove me

File: tests/features/camel-flatpack/src/test/java/org/apache/karaf/camel/itest/CamelFlatpackITest.java [hunk 2]
```diff
@@ -46,20 +46,21 @@ public class CamelFlatpackITest extends AbstractCamelSingleFeatureResultMockBase
...
-            assertEquals(EXPECTED_ITEM_DESCRIPTIONS[counter], "ITEM_DESC", body.get("ITEM_DESC"));
+            assertEquals("ITEM_DESC", EXPECTED_ITEM_DESCRIPTIONS[counter], body.get("ITEM_DESC"));
             counter++;
         }
-    }
-
-    @Test
-    public void testResultMock() throws Exception {
-        assertMockEndpointsSatisfied();
+        assertEquals(4,counter);
```
Comment (essobedo) [inline tests/features/camel-flatpack/src/test/java/org/apache/karaf/camel/itest/CamelFlatpackITest.java:63]:
```suggestion
        assertEquals(4, counter);
```

File: tests/camel-integration-test/src/main/java/org/apache/karaf/camel/itests/AbstractCamelSingleFeatureResultMockBasedRouteITest.java [hunk 3]
```diff
@@ -34,4 +34,5 @@ public void setupMock() {
     public void cleanMock() {
         CamelSingleFeatureResultMockBasedRoute.super.cleanMock();
     }
+
```
Comment (essobedo) [inline tests/camel-integration-test/src/main/java/org/apache/karaf/camel/itests/AbstractCamelSingleFeatureResultMockBasedRouteITest.java:37]:
```suggestion
```

**Review by essobedo — APPROVED** [review]
